x-common: &common
  entrypoint: ["/bin/bash", "-c"]
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "../:/MPlib"
  working_dir: /MPlib
  network_mode: host

services:
  sphinx:
    <<: *common
    command:
      - >-
        python3 -m pip install ./wheelhouse/mplib*.whl
        && rm -rf ./docs/build
        && sphinx-autobuild ./docs/source/ ./docs/build/html/
    image: kolinguo/sphinx
    build:
      network: host
      dockerfile_inline: |
        FROM ubuntu:latest
        RUN apt-get update && apt-get install -y --no-install-recommends \
            git python3 python3-pip \
          && apt-get upgrade -y \
          && rm -rf /var/lib/apt/lists/* \
          && python3 -m pip install --upgrade pip
        COPY ./requirements.txt /tmp
        RUN python3 -m pip install -r /tmp/requirements.txt \
          && rm -r /tmp/*
        RUN git config --global --add safe.directory /MPlib
