name: build-and-publish

on:
  push:
    branches: [testing]
    tags: ['v*']

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pyver: [cp37, cp38, cp39, cp310, cp311, cp312]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: ${{ matrix.pyver }}-*
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.pyver }}-${{ strategy.job-index }}
          path: wheelhouse/*
      - name: Test
        run: |
          python -m pip install --user wheelhouse/*.whl
          python -m unittest discover -v -s mplib/tests
